### ISSUE TITLE
Caddy vs Nginx for HTTP/1

### ISSUE THREAD

**Issue by kokizzu** [pebble/loadbalancer-benchmarks#2]
it would be nice to compare caddy too instead of just nginx and haproxy for http/1

thank you for making these benchmarks 👍

**Comment by DeviaVir** [comment]
Caddy is only available as an HTTP/2 server, so I'm not sure what you're asking here.

See: https://github.com/mholt/caddy

**Comment by kokizzu** [comment]
Caddy can also be used without http/2

https://caddyserver.com/docs/faq
![image](https://cloud.githubusercontent.com/assets/1061610/16193975/5cca230c-371c-11e6-98d3-5ff2203bc547.png)

**Comment by DeviaVir** [comment]
I don't think there's a general interest for Caddy to run in HTTP/1 (which it's not designed for) against a webserver that clearly is. However, since it's all opensource, feel free to PR your findings and I'll be happy to merge them in!
